### ISSUE TITLE
Roadmap :)

### ISSUE THREAD

**Issue by afonsopacifer** [all-animation/all-animiation.github.io#2]
# New features and improvements

- [ ] Exclude all files from build the all-animatin core, and use the lib from CDN or bower.
- [ ] Organize all Front-End dependencies (bower)
- [ ] Use ES6 syntax in gulpfile.json
- [ ] Add new features in gulp configs:
 - [ ] Static server with livereload
 - [ ] imagemin
 - [ ] htmlhint
 - [ ] cssnext
 - [ ] csslint
 - [ ] uncss
 - [ ] jshint
